Fix ART-Extension build failure when CAPSTONE is undefined
AutoFastJniDetectTask defined always, but it uses IsFastJNI which is
defined only if CAPSTONE is defined. And if CAPSTONE is not defined it
causes compilation error. So AutoFastJniDetectTask have to be defined
only if CAPSTONE is.

Change-Id: I4444538e91ecc186f73fc6407826e06cd6cc804f
Extension-Weekly: 1639.5
Expected-Impact: fix compilation error when CAPSTONE is not defined
Orig-Tracked-On: https://jira01.devtools.intel.com/browse/CAR-4361
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-38206
Category: device enablement
Domain: AOSP.ART-ME
Origin: internal
Upstream-Candidate: no, proprietary
Signed-off-by: Daniil Suchkov <daniil.suchkov@intel.com>
Reviewed-on: https://android.intel.com/540777
Reviewed-by: Rouban, Yevgeny Y <yevgeny.y.rouban@intel.com>
Reviewed-by: lab_aqa <lab_aqa@intel.com>
Reviewed-by: Ivanov, Vladimir A <vladimir.a.ivanov@intel.com>
Reviewed-by: Kazantsev, Maxim <maxim.kazantsev@intel.com>
Reviewed-by: Shamin, Anton <anton.shamin@intel.com>
Reviewed-by: Ivaschenko, Aleksei V <aleksei.v.ivaschenko@intel.com>
Tested-by: Popov, Ivan G <ivan.g.popov@intel.com>
Reviewed-on: https://android.intel.com:443/542114